### ISSUE TITLE
Add Package Discovery

### ISSUE THREAD

**Issue by populov** [Saritasa/php-laravel-tools#1]
Add **laravel -> providers** section in *composer.json* to enable package discovery
https://laravel.com/docs/5.6/packages#package-discovery

**Comment by VladimirBerdnik** [comment]
Package discovery [was added](https://github.com/Saritasa/php-laravel-tools/commit/d49dd0de382d6a56ba0911619e65d448ce31d88d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)
