### ISSUE TITLE
Generate new entity - Dto for models

### ISSUE THREAD

**Issue by VladimirBerdnik** [Saritasa/php-laravel-tools#8]
We can generate Dto for models to simplify data transfer. Any suggestions?)

**Comment by populov** [comment]
I'm all for it.

**Comment by VladimirBerdnik** [comment]
Base functionality for DTO generation was added in [1.0.0](https://github.com/Saritasa/php-laravel-tools/releases/tag/1.0.0) reliese.
My next steps for this functionality is:

1. Allow to decide properties visibility type (public\protected) from artisan command
2. Allow to generate typehinted getters and settes for DTO

**Comment by VladimirBerdnik** [comment]
Feature was added in [1.1.0](https://github.com/Saritasa/php-laravel-tools/releases/tag/1.1.0) release
